version: "3"

services:
    client:
        image: nginx
        ports:
            - 8000:80
        volumes:
            - ./content:/usr/share/nginx/html
            - ./conf/nginx.conf/:/etc/nginx/nginx.conf
